from app.schema.query_response import (
    QueryAnalysis,
    RetrievedDocument,
    QueryResponse,
    RetrievalResult,
    UserQueryResponse,
    Citation,
    LLMAnswer,
)

from app.tools.tools import (
    search_vector,
    search_fts,
    search_hybrid,
)

from langchain_core.tools import tool
from langchain.agents import create_agent
from langchain_openai import ChatOpenAI
from langsmith import traceable
import json
from langchain_core.messages import ToolMessage

# from pprint import pprint


class RagAgent:

    def __init__(self):
        self.llm = ChatOpenAI(model="gpt-5.5", temperature=0)

        self.regulatory_agent = create_agent(
            model=self.llm,
            tools=[
                search_vector,
                search_fts,
                search_hybrid,
            ],
            response_format=LLMAnswer,
            system_prompt="""You are a Banking Regulatory FAQ Assistant.

            Your purpose is to provide a concise and accurate answer user questions 
            using only the available regulatory documents in a direct manner.

            Your workflow is fixed and must be followed exactly.

            ========================
            STEP 1 - Analyze Query
            ========================

            Analyze the user's question to determine the most appropriate retrieval strategy.

            If the user's question is unrelated to banking or banking regulations:

            - Do not call any retrieval tool.
            - Respond directly with the structured response.
            - Leave retrieval empty.

            Choose exactly ONE retrieval tool.

            Use:

            • search_vector
            For conceptual questions requiring explanation, comparison, summaries, intent or meaning.

            Examples:
            - What is Tier 1 Capital?
            - Explain KYC requirements.
            - Difference between CRR and SLR.

            • search_fts
            For questions containing exact searchable identifiers such as:

            - regulatory acronyms
            - regulation names
            - framework names
            - Act names
            - circular numbers
            - section numbers
            - clause numbers
            - dates
            - percentages
            - monetary values
            - proper nouns

            Examples:
            - RBI Circular DOR.CRE.REC.28/...
            - Section 35A
            - 9% CRAR

            • search_hybrid
            When the question contains both conceptual language and exact identifiers.

            Example:
            Explain the provisioning requirements under RBI Circular XXX.

            ========================
            STEP 2 - Retrieval
            ========================

            Call exactly ONE retrieval tool.

            Never call more than one tool.

            Never retry another retrieval tool.

            Never compare multiple retrieval results.

            Never call another retrieval tool after one has returned results.

            ========================
            STEP 3 - Generate Answer
            ========================

            Read the retrieved documents.

            Generate the answer ONLY from the retrieved content.

            Do not use external knowledge.

            Do not infer.

            Do not speculate.

            Do not complete missing information.

            If the answer is not present in the retrieved documents, respond exactly:

            "I could not find this information in the available regulatory documents."

            Answer uses the minimum number of words necessary to convey the complete answer.

            Answer should omit pleasantries, hedging language, and unnecessary context.

            Answer should exclude meta-commentary about the answer or the model's capabilities.

            Answer should not include explanations unless explicitly requested.

            ========================
            Response
            ========================

            Return only the structured response.

            The answer should be concise and only contain the requested info.
            
            rule_summary
            - extract important regulatory rules
            - thresholds
            - limits
            - conditions
            - obligations

            Do NOT generate:

            - citations
            - page numbers
            - confidence scores
            - document names
            - source references

            These are generated by the application.""",
        )

    def invoke(self, query: str):

        llm = ChatOpenAI(
            model="gpt-5.5",
            temperature=0,
        )

        result = self.regulatory_agent.invoke(
            {
                "messages": [
                    {
                        "role": "user",
                        "content": query,
                    }
                ]
            }
        )
        # pprint(result)
        llm_response = result["structured_response"]

        tool_messages = [
            message
            for message in result["messages"]
            if isinstance(message, ToolMessage)
        ]

        if len(tool_messages) == 0:
            # Agent intentionally chose not to retrieve
            retrieval = RetrievalResult(retrieval_strategy="NONE", documents=[])

        elif len(tool_messages) == 1:
            tool_output = json.loads(tool_messages[0].content)

            retrieval = RetrievalResult(
                retrieval_strategy=tool_messages[0].name,
                documents=[
                    RetrievedDocument.model_validate(doc)
                    for doc in tool_output["documents"]
                ],
            )

        else:
            raise RuntimeError(
                f"Expected at most one retrieval tool call, found {len(tool_messages)}."
            )

        citations = self.build_citations(retrieval.documents)

        query_response = QueryResponse(
            answer=llm_response.answer,
            rule_summary=llm_response.rule_summary,
            citations=citations,
            confidence_score=self.calculate_confidence(retrieval),
        )

        return UserQueryResponse(
            retrieval=retrieval,
            query_response=query_response,
        )

    def build_citations(self, documents: list[RetrievedDocument]):
        seen = set()
        citations = []

        for doc in documents:

            metadata = doc.metadata

            key = (
                metadata.get("source"),
                metadata.get("page"),
                metadata.get("section"),
            )

            if key in seen:
                continue

            seen.add(key)

            citations.append(
                Citation(
                    source=metadata.get("source", "Unknown Source"),
                    page=metadata.get("page", 0) + 1,
                    section=metadata.get("section", ""),
                    excerpt=doc.content[:250].strip(),
                )
            )
        return citations

    def calculate_confidence(self, retrieval: RetrievalResult):

        scores = [
            doc.retrieval_score
            for doc in retrieval.documents
            if doc.retrieval_score is not None
        ]

        if not scores:
            return 0.0

        top_score = max(scores)

        avg_score = sum(scores) / len(scores)

        coverage = min(len(scores) / 5, 1)

        confidence = 0.6 * top_score + 0.3 * avg_score + 0.1 * coverage

        # compress extreme differences
        confidence = 0.5 + (confidence * 0.5)
        return round(confidence, 2)
